### ISSUE TITLE
How to use exists uv_loop_t .

### ISSUE THREAD

**Issue by yihuang** [luvit/luv#252]
I already have a uv_loop_t instance created by c, how can i access this loop instance through luv api.
Because luv store uv_loop_t in userdata. If I change userdata to store pointer of uv_loop_t, it would be many changes.

**Comment by creationix** [comment]
As it stands now, this isn't supported.  I wonder if I could add an API to provide a `uv_loop_t` instance from the C interface.

**Comment by rocaltair** [comment]
@yihuang 
Maybe you can do that like this:

```c
lua_State *L = luaL_newstate();
...
luaopen_luv(L);
...
uv_loop_t loop = luv_loop(L); /* create loop by luv*/
...
luaL_dofile(L, lua_file_path); /*new uv_handle in lua*/
...
uv_run(loop);
```

don't invoke luv.run() in lua

**Comment by Dijky** [comment]
I'm reviving this issue because I'm interest in sharing the loop as well.

On the luv side of things, I reckon that [`luaopen_luv`](/luvit/luv/blob/master/src/luv.c#L523), [`loop_gc`](/luvit/luv/blob/master/src/luv.c#L501), and Lua's garbage collection are the critical points.

- `luaopen_luv` allocates the loop through `lua_newuserdata`,
- `loop_gc` closes all handles on the loop when it is garbage collected,
- Lua will garbage collect the loop once it becomes inaccessible in Lua.

After calling `luaopen_luv`, you should be able to manipulate or even replace the loop struct, but you have to use the same address.  
My initial idea was to `memcpy` a selfmade `uv_loop_t` over luv's loop, but I found no documentation indicating that a loop can be safely copied/moved in memory. In fact, some members' types like `uv_mutex_t` (a typedef for `pthread_mutex_t` on UNIX) are *not* safe to be moved on some systems.

What you can do is call `uv_loop_init` to reset luv's loop (this function will actually copy the `data` member that holds the `lua_State*`) and/or call any `uv_*` function to manipulate luv's loop. 

<hr>

The only apparently safe method would be to replace the `uv_loop_t` stored in Lua userdata with a `uv_loop_t*`, so that a custom loop can be provided. This also means the caller of `luaopen_luv` can use (and must free) the loop after the userdata has been garbage-collected.

The API could be changed such that a custom `uv_loop_t*` and GC callback can be provided. Now the user is responsible for freeing the loop sometime after GC.  
Otherwise, without a custom loop, luv will create and free its own loop like it does now.

**Comment by zhaozg** [comment]
I think is issue should please now, the master branch support loop outside of luv.

1. create your uv_loop_t* loop out of luv.
2. call luv_set_loop(L, loop) before luaopen_luv.
3. call luvopen_luv, luvopen_luv will check wether need to create loop in luv. loop outside of luv will not be gc. so caller should manage it.

Feel free to reopen it.
