### ISSUE TITLE
lua_equal expected in luv_check_handle

### ISSUE THREAD

**Issue by rocaltair** [luvit/luv#255]
lua_equal expected [here](https://github.com/luvit/luv/blob/master/src/handle.c#L41) in luv_check_handle?

**Comment by creationix** [comment]
Could you explain what you mean.  I don't understand.

**Comment by aiverson** [comment]
I think the question is asking why the handle's metatable is being indexed rather than checked for equality `REGISTRY["uv_handle"][getmetatable(handle)] == true` rather than `getmetatable(handle) == REGISTRY["uv_handle"]` The answer to this interpretation of the question is that there is more than one type of uv_handle. A bunch of different types with different methods and different metatables are all handles. To tag something as a handle, the metatable initialization code [here](https://github.com/luvit/luv/blob/master/src/luv.c#L451) stores every handle metatable as a key in REGISTRY["uv_handle"] with a value of true. Therefore, presumably every metatable for a type of uv_handle is a key in REGISTRY["uv_handle"] set to true but no other metatable is unless someone goes out of their way to break it, which would require either using the C API or the debug library.

**Comment by zhaozg** [comment]
It’s been inactive for too long, so it’s closed.
