### ISSUE TITLE
API luv.setup_args is missing

### ISSUE THREAD

**Issue by hyee** [luvit/luv#264]
The libuv [doc](http://docs.libuv.org/en/v1.x/misc.html) describes that uv_setup_args must be called before calling  `set_process_title/get_process_title`, as my test that without this API in Windows it is fine, but in Linux  the 2 functions don't work and even crash in some cases.

**Comment by squeek502** [comment]
Worth noting that `uv_setup_args` is called in [Luvi's main](https://github.com/luvit/luvi/blob/master/src/main.c#L148), similarly to what [node does](https://github.com/nodejs/node/blob/c8a00fdf62ff2645fe4be515811429d08ba3d641/src/node.cc#L4928), so if you're using Luvi, this should be taken care of.

Also seems like this is something that should be done on the C side rather than the Lua side (for reference, see [the implementation of uv_setup_args](https://github.com/libuv/libuv/blob/v1.x/src/unix/proctitle.c#L37-L80))

**Comment by hyee** [comment]
I only use luv dynamic library in my project,  it seems like the `main` function is not called with the `local uv = require('luv')` syntax, is there any way to correctly call `set_process_title` in such case? Thanks.

**Comment by hyee** [comment]
I managed to find another way to accomplish the purpose, thanks and I'm closing this ticket.
