### ISSUE TITLE
segfault on luv_check_handle

### ISSUE THREAD

**Issue by Bilal2453** [luvit/luv#633]
I've been playing a bit with `luv.handle_get_type`/`luv.fileno` and I noticed that on Lua 5.1/LuaJIT it segfaults with
```lua
luv.handle_get_type(newproxy())
-- or
luv.fileno(newproxy())
```

I traced this back a bit to find it happens in `luv_check_handle`, more specifically on 
```c
if (!handle->data) { goto fail; }
```

I assume this only really happens when passing an empty userdata like with `newproxy`? Why exactly it happens or how it could be possibly fixed is beyond me though, I speculated that this is trying to index the userdata memory block out of bounds but not entirely sure if that is how userdata works.

**Comment by squeek502** [comment]
AFAICT this check does nothing (it can never fail):

https://github.com/luvit/luv/blob/e8e7b7e13225348a8806118a3ea9e021383a9536/src/handle.c#L36

so it's basically unconditionally assuming all userdata is a `uv_handle_t` and trying to access the `data` member. 

I think we should move the `isHandle` check higher:

https://github.com/luvit/luv/blob/e8e7b7e13225348a8806118a3ea9e021383a9536/src/handle.c#L47-L52

so that it actually excludes non-handles before accessing the `data` field.

**Comment by Bilal2453** [comment]
Should we also make sure `lua_getfield` returns a `LUA_TTABLE`? As we also need to make sure `lua_getmetatable` does not return NULL making `lua_rawget` segfault anyways.

I currently have the following:

```c
  if (!(udata = lua_touserdata(L, index))) { goto fail; }
  if (lua_getfield(L, LUA_REGISTRYINDEX, "uv_handle") != LUA_TTABLE) { goto fail; }
  if (!lua_getmetatable(L, index < 0 ? index - 1 : index)) { goto fail; }
  lua_rawget(L, -2);
  isHandle = lua_toboolean(L, -1);
  lua_pop(L, 2);
  if (!(handle = *(uv_handle_t**) udata)) { goto fail; }
  if (!handle->data) { goto fail; }
  if (isHandle) { return handle; }
  fail: luaL_argerror(L, index, "Expected uv_handle userdata");
  return NULL;
  ```
  
  This does work for the above scenario, works fairly well too, but it still can't handle inputs like `newproxy(true)`, it will segfault on that.  `newproxy(true)` creates an empty metatable and we don't really check beyond that.

How should we handle this?  (I am actually just learning how to use the Lua API so this issue is coming in handy teaching me)

**Comment by squeek502** [comment]
Your code looks like it should work to me. I'm not hitting any problems locally with it even with `newproxy(true)`.

By the way, it's safe to assume the `"uv_handle"` metatable has been registered, since [it's done at `luv` initialization](https://github.com/luvit/luv/blob/e8e7b7e13225348a8806118a3ea9e021383a9536/src/luv.c#L861).

**Comment by Bilal2453** [comment]
Ah I see, makes sense.  Apparently it does actually work, I just had to clear the building cache.

I should I PR a cleaned version of this + fixing `luv_check_stream` later on?  I may be busy today
