### ISSUE TITLE
How to pass command line string to uv.spawn？

### ISSUE THREAD

**Issue by linrongbin16** [luvit/luv#673]
Hi, I read the docs and it looks like it's mandatory to pass list of args to uv.spawn.

But if I have some command line strings:

```bash
git log --pretty='%C(yellow)%h %C(cyan)%cd %C(green)%aN%C(auto)%d %Creset%s' --date=short

rg --no-heading --column -- 'fzf'
```

How to pass the command string directly to uv.spawn?

I am writing a Neovim plugin with luv, so I don't have a library manager like luarock. All I have is Neovim environment.

I feel like parsing command line string is quite difficult, I cannot just split the string by whitespace.

**Comment by squeek502** [comment]
Going from a string with quotes, etc to a list of arguments is typically handled by the shell, and each shell can do things differently (how to escape things, what needs to be escaped, etc), so there's no one *correct* way to do it AFAIK.

I believe what you'd want for those two command would be:

```lua
{
  "git",
  "log",
  "--pretty=%C(yellow)%h %C(cyan)%cd %C(green)%aN%C(auto)%d %Creset%s",
  "--date=short",
}
```
and
```lua
{
  "rg",
  "--no-heading",
  "--column",
  "--",
  "fzf",
}
```

**Comment by linrongbin16** [comment]
Hi, thanks to confirm.

I have one more question, how does the quotes and escaping characters handled by uv.spawn?

So in your sample code, there's no single quote `'` around the `%C(yellow)%h %C(cyan)%cd %C(green)%aN%C(auto)%d %Creset%s`?

So inside uv.spawn, it will automatically add quotes for me?

**Comment by squeek502** [comment]
Quotes are only necessary when determining if something is a single argument or multiple arguments. Once the arguments have been split, then quotes are no longer necessary. This splitting (and therefore removal of quotes) is what the shell usually does for you.

For example, if you run something like:
```
myprogram "some argument"
```
then in `myprogram` you'd get `some argument` (without the quotes) as argv[1].

So, when calling `uv.spawn`, you just call it with the arguments already split, so there's no need for quotes.

There is a caveat for Windows, though, since [it does actually transform it back into a single string before giving it to `CreateProcess`](https://github.com/luvit/luv/blob/master/docs.md#uvspawnpath-options-on_exit). See the `options.verbatim` flag if you need to do your own quoting for Windows:

> options.verbatim - If true, do not wrap any arguments in quotes, or perform any other escaping, when converting the argument list into a command line string. This option is only meaningful on Windows systems. On Unix it is silently ignored.

You'll probably need to test it on Windows to make sure it does what you expect.

---

Oh also, the docs are wrong about `options.args`: the first value should not be the command/program name. Instead you'll want to do something like this:

```lua
uv.spawn("git", {
  args = {
    "log",
    "--pretty=%C(yellow)%h %C(cyan)%cd %C(green)%aN%C(auto)%d %Creset%s",
    "--date=short",
  },
})
```

will update the docs about that.

**Comment by linrongbin16** [comment]
thanks for education, much clear for me
