### ISSUE TITLE
How to use stat results?

### ISSUE THREAD

**Issue by tjakway** [luvit/luv#741]
How are you supposed to use the mode field in the stat result table returned by uv.fs_stat? Unlike python’s stat module, luv doesn’t export any access functions, constants, or masks like [S_IMODE](https://docs.python.org/3/library/stat.html#stat.S_IMODE) or [S_IRWXU](https://docs.python.org/3/library/stat.html#stat.S_IRWXU). Unless I'm missing something you'd have to import those from a C header or hardcode them. And even if you do import or copy them from C, Lua <5.3 doesn't have bitwise operators.
I don't think the docs say how to handle this.

**Comment by truemedian** [comment]
The mode field returned is identical to the POSIX definition (on all systems, including windows). This means it's a bitfield of
```
 SLFBDCF   U G T   R W X   R W X   R W X
file type  mode    user    group   other
```

Where: 
```
S = 0xC000 socket
L = 0xA000 symlink
F = 0x8000 regular file
B = 0x6000 block device
D = 0x4000 directory
C = 0x2000 character device
F = 0x1000 fifo

U = 0x800 suid
G = 0x400 sgid
T = 0x200 sticky

R = 0x100 (user), 0x20 (group), 0x4 (other)
W = 0x80 (user), 0x10 (group), 0x2 (other)
X = 0x40 (user), 0x8 (group), 0x1 (other)
```

You're really meant to interact with it using a bitwise library, but if you're on 5.1 (5.2 has bit32, 5.3+ has native bitwise) and don't want to use one of the pure lua bitwise operations libraries, you could always `string.format('%o', mode)` and operate on the octal representation `FFMUGO`.

I could see the desire to have these added to the list of constants though, because unless they're handed down from on high or you go digging through the libuv documentation you wouldn't know.
